spring:
  kafka:
    bootstrap-servers: localhost:9092  # Kafka 服务器地址
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: equipment-data-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.qum.iotdataprocessingsystem.pojo"
  application:
    name: IotDataProcessingSystem
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/iotdb
    username: postgres
    password: 1006
    driver-class-name: org.postgresql.Driver
  influxdb:
    url: http://localhost:8086
    database: equipments
    retention-policy: autogen
  data:
    redis:
      database: 0
      port: 6379
      host: localhost

server:
  port: 8081
